### ISSUE TITLE
No client_aatool folder made for aatool to look at

### ISSUE THREAD

**Issue by CreeperNinjaYT** [fxmorin/Client_AATool#1]
I am running fabric 1.18.2 with the client aatool in the mods folder, I launch Minecraft, I run /aatool true but no client_aatool folder is made for aatool to get the advancements from.

I have tested it with 1.18.1 and 1.18, both same issues

**Comment by FxMorin** [comment]
Did you join a server? The mod only works on servers since aatool works fine without the mod for singleplayer

**Comment by CreeperNinjaYT** [comment]
Yes, this is when I join a server

**Comment by Herfo** [comment]
Same. Just tried doing the same in 1.18.2 and it didn't created the client_aatool directory.

**Comment by CreeperNinjaYT** [comment]
Weird, now it is working

**Comment by Herfo** [comment]
> Weird, now it is working

What have you done different?

**Comment by CreeperNinjaYT** [comment]
> > Weird, now it is working
> 
> What have you done different?

I don't know, I just forgot about it for a few days, then I tried it again and it worked, try run Minecraft on the server that you want, say for an hour or so and try /aatool true again

**Comment by Herfo** [comment]
Just solved my problem too. I needed to run Minecraft as an admin in Windows. That's why he coundn't create the folder :D

**Comment by FxMorin** [comment]
Oh good to know
